### 상품 리스트 조회
GET https://dummyjson.com/products?sortBy=title&order=asc&limit=3
Content-Type: application/json

### 상품 등록
POST https://dummyjson.com/products/add
Content-Type: application/json

{
  "title": "새로운 상품",
  "description": "상품 설명입니다",
  "price": 59.99,
  "discountPercentage": 10.28,
  "rating": 3.78,
  "category": "electronics",
  "brand": "테스트 브랜드",
  "stock": 100,
  "availabilityStatus": "In Stock",
  "thumbnail": "https://cdn.dummyjson.com/products/images/sports-accessories/American%20Football/1.png",
  "images": [
    "https://cdn.dummyjson.com/products/images/sports-accessories/American%20Football/1.png",
    "https://cdn.dummyjson.com/products/images/sports-accessories/American%20Football/1.png"
  ]
}

### 상품 수정
PUT https://dummyjson.com/products/1
Content-Type: application/json

{
  "title": "새로운 상품",
  "description": "상품 설명입니다",
  "price": 59.99,
  "discountPercentage": 10.28,
  "rating": 3.78,
  "category": "electronics",
  "brand": "테스트 브랜드",
  "stock": 100,
  "availabilityStatus": "In Stock",
  "thumbnail": "https://cdn.dummyjson.com/products/images/sports-accessories/American%20Football/1.png",
  "images": [
    "https://cdn.dummyjson.com/products/images/sports-accessories/American%20Football/1.png",
    "https://cdn.dummyjson.com/products/images/sports-accessories/American%20Football/1.png"
  ]
}

### 상품 삭제
DELETE https://dummyjson.com/products/1
Content-Type: application/json

### 상품 1개 조회
GET https://dummyjson.com/products/1
Content-Type: application/json